### ISSUE TITLE
Build: commit a49d1c5 has broken build on ubuntu 12.04

### ISSUE THREAD

**Issue by mwf** [reverbrain/elliptics#252]
Build is broken by commit: https://github.com/reverbrain/elliptics/commit/a49d1c5b8689e9d41a6ab881954587b13c2b4bbd

make's output:

```
...
[  3%] Building C object library/CMakeFiles/elliptics_client.dir/crypto.c.o
[  5%] Building C object library/CMakeFiles/elliptics_client.dir/crypto/sha512.c.o
/home/ikorolev/repos/elliptics/library/crypto/sha512.c: In function ‘sha512_process_bytes’:
/home/ikorolev/repos/elliptics/library/crypto/sha512.c:388:7: warning: implicit declaration of function ‘dnet_offsetof’ [-Wimplicit-function-declaration]
/home/ikorolev/repos/elliptics/library/crypto/sha512.c:388:11: error: expected expression before ‘struct’
make[2]: *** [library/CMakeFiles/elliptics_client.dir/crypto/sha512.c.o] Error 1
make[1]: *** [library/CMakeFiles/elliptics_client.dir/all] Error 2
make: *** [all] Error 2
```
