### ISSUE TITLE
Elliptics fails to build on Mac OS X 10.9.2

### ISSUE THREAD

**Issue by mwf** [reverbrain/elliptics#397]
Hi!

Guys, do you support Mac OS X?

I can't build elliptics because of epoll.h absence =(

```
➜  build git:(lts) make
Scanning dependencies of target elliptics_cocaine
[  1%] Building CXX object srw/CMakeFiles/elliptics_cocaine.dir/srw.cpp.o
In file included from /Users/ikorolev/repos/elliptics/srw/srw.cpp:48:
/Users/ikorolev/repos/elliptics/srw/../library/elliptics.h:25:10: fatal error: 'sys/epoll.h' file not found
#include <sys/epoll.h>
         ^
1 error generated.
make[2]: *** [srw/CMakeFiles/elliptics_cocaine.dir/srw.cpp.o] Error 1
make[1]: *** [srw/CMakeFiles/elliptics_cocaine.dir/all] Error 2
make: *** [all] Error 2
```
